spring:
  datasource:
    url: jdbc:h2:mem:school
    username: sa
    driver-class-name: org.h2.Driver
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true